// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvooukHajXR6E4rh2k-AOTsNUskX689Xg',
    appId: '1:217589708524:web:4db672a2490269efacd7c9',
    messagingSenderId: '217589708524',
    projectId: 'msakin-2b6ae',
    authDomain: 'msakin-2b6ae.firebaseapp.com',
    storageBucket: 'msakin-2b6ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJR0t2y730zyjFoK5SYvOTwoe5bZHMCIk',
    appId: '1:217589708524:android:15b42e52e0dfd962acd7c9',
    messagingSenderId: '217589708524',
    projectId: 'msakin-2b6ae',
    storageBucket: 'msakin-2b6ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhSH0Rg57cMgwANb82H7fiXuL0Vl3TYUY',
    appId: '1:217589708524:ios:f4eeba0969e350eaacd7c9',
    messagingSenderId: '217589708524',
    projectId: 'msakin-2b6ae',
    storageBucket: 'msakin-2b6ae.firebasestorage.app',
    iosBundleId: 'msakin.al.rfahih.zizo.msakinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvooukHajXR6E4rh2k-AOTsNUskX689Xg',
    appId: '1:217589708524:web:983acdd8f117de28acd7c9',
    messagingSenderId: '217589708524',
    projectId: 'msakin-2b6ae',
    authDomain: 'msakin-2b6ae.firebaseapp.com',
    storageBucket: 'msakin-2b6ae.firebasestorage.app',
  );
}
